name: Deploy React App by workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Clean remote directory
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/pull/') || github.event_name == 'workflow_dispatch'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf /home/${{secrets.DEPLOY_USER}}/notice-project/github-actions-study/*

      - name: Deploy to local server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./*"
          target: "/home/${{secrets.DEPLOY_USER}}/notice-project/github-actions-study/"

      - name: Start server on local server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{secrets.DEPLOY_USER}}/notice-project/github-actions-study
            npm install
